const subjects = [
    "Love",
    "Hate",
    "Sex",
    "Drugs",
    "Prosperity",
    "Despair",
    "Fable - Fictional story with a lesson",
    "Third-person narrative",
    "Something that annoys you",
    "Something that brings you joy",
    "Something that brings you pain",
    "A Time When You Were Wrong",
    "Party Song",
    "Nonsense",
    "Tribute or Gratitude",
    "Fantastical Adventure",
    "Getting into trouble",
    "The Best or Worst Part of the Human Experience",
    "Identify a Problem and Propose a Solution",
    "Historical Figure or Event",
    "Philosophy",
    "Mental Illness",
    "Common Ground",
    "A Line in the Sand",
    "Giving Up",
    "Moving On",
    "Standing your ground",
    "Extended Metaphor",
    "Something you learned",
    "Something you accomplished"
]